language: python
python:
  - "3.3"
services:
  - rabbitmq # will start rabbitmq-server
before_script:
  - psql -c 'create database taiga;' -U postgres
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script:
    - coverage run --source=taiga --omit='*tests*,*commands*,*migrations*,*admin*,*.jinja,*dashboard*,*settings*,*wsgi*,*questions*,*documents*' manage.py test --settings=settings.travis taiga
notifications:
  email:
    recipients:
      - jespinog@gmail.com
      - andrei.antoukh@gmail.com
      - bameda@dbarragan.com
      - anler86@gmail.com
    on_success: change
    on_failure: change
after_success:
  - coveralls
