language: python
python:
  - "3.3"
services:
  - rabbitmq # will start rabbitmq-server
before_script:
  - psql -c 'create database greenmine;' -U postgres
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=greenmine manage.py test --settings=greenmine.settings.travis greenmine
notifications:
  email:
    recipients:
      - jespinog@gmail.com
      - andrei.antoukh@gmail.com
      - bameda@dbarragan.com
    on_success: change
    on_failure: change
after_success:
  - coveralls
