language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=greenmine manage.py test --settings=greenmine.settings.testing greenmine
notifications:
  email:
    recipients:
      - jespinog@gmail.com
    on_success: change
    on_failure: change
after_success:
  - coveralls
